---
abstract: 'Respite based client/server in Perl'
author:
  - "['Paul Seamons <paul@seamons.com>', 'Jason Hall  <jayce@cpan.org>',]"
build_requires:
  Sub::Override: '0'
  Test::Deep: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.033, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Respite
requires:
  CGI::Ex: '0'
  Data::Debug: '0'
  Digest::MD5: '0'
  End: '0'
  FindBin: '0'
  IO::Interactive: '0'
  IO::Socket::SSL: '0'
  JSON: '0'
  Net::Server: '0'
  Scalar::Util: '0'
  Throw: '0'
  Time::HiRes: '0'
  perl: '5.0080'
resources:
  bugtracker: https://github.com/hookbot/perl-Respite/issues
  homepage: https://github.com/hookbot/perl-Respite
  repository: https://github.com/hookbot/perl-Respite.git
version: '0.22'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
