---
abstract: 'Respite based client/server using'
author:
  - "['Paul Seamons <paul@seamons.com>', 'Jason Hall  <jayce@cpan.org>',]"
build_requires:
  Sub::Override: '0'
  Test::Deep: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Respite
requires:
  CGI::Ex: '0'
  Data::Debug: '0'
  Digest::MD5: '0'
  End: '0'
  FindBin: '0'
  IO::Interactive: '0'
  IO::Socket::SSL: '0'
  JSON: '0'
  Net::Server: '0'
  Scalar::Util: '0'
  Throw: '0'
  Time::HiRes: '0'
  perl: '5.0080'
resources:
  bugtracker: https://github.com/Jayceh/Respite/issues
  homepage: https://github.com/Jayceh/Respite
  repository: https://github.com/Jayceh/Respite.git
version: '0.2'
